Repository JasonDsouza212/free-hit, pull requests merged in 2023-08, with the labels that each got.

#1538 fix: side menu active Tabs #1532
  src/components/Sidebar.jsx
  src/styles/header.css
Labels: level2, gssoc23

#1552 fix: search input empty issue #1542
  src/components/Navbar.jsx
  src/components/Sidebar.jsx
Labels: level2, gssoc23

#1533 feat: Added a socials section and badges to that section in the readme
  README.md
Labels: level1, gssoc23

#1550 feat: search Feature Added #1544
  src/pages/Community.jsx
  src/styles/Community.css
Labels: level3, gssoc23

#1569 fix: Fixes#1562 by adding links, logo and changing name
  src/DB/product.json
Labels: level1, gssoc23

#1564 fix: Updated the class attribute to className in the JSX code #1563
  src/pages/NotFound.jsx
Labels: level1, gssoc23

#1549 feat: Added the Table of content to the readme.md
  README.md
Labels: level1, gssoc23, no-pr-activity

#1588 feat: implement dedicated share model component for sharing links 🚀🔥
  src/components/Card/GridView.jsx
  src/components/Card/ListView.jsx
  src/components/Card/ShareModel.jsx
  src/styles/GridView.css
  src/styles/shareModel.css
Labels: level3, gssoc23

#1579 feat: pagination feature added #1567
  src/pages/Community.jsx
Labels: level3, gssoc23

#1599 feat: bookMark #1597
  src/App.jsx
Labels: level3, gssoc23
