Repository JasonDsouza212/free-hit, pull requests merged in 2023-07, with the labels that each got.

#1005 Freelance useful tool added
  src/DB/product.json
Labels: level1, gssoc23

#987 Close the sidebar once filter is selected
  src/components/Sidebar.jsx
  src/styles/header.css
Labels: level2, gssoc23

#1003 New AI tool added
  src/DB/product.json
Labels: level1, gssoc23, title-needs-formatting

#1099 chore: added sejda #920
  src/DB/product.json
Labels: level1, gssoc23

#1137 fix: added lazy loading #799
  src/App.jsx
Labels: level2, gssoc23

#1141 feat: make social anchors accessible on footer✨
  src/components/Footer.jsx
Labels: level2, gssoc23

#1206 feat: Added course platform in sidebar
  src/DB/product.json
  src/utils/data/categories.js
  src/utils/data/filters.js
Labels: Add tool 🛠️, level1, gssoc23

#1214 feat: make social anchors accessible for profile cards on team.jsx ✨
  src/components/Team.jsx
Labels: level1, gssoc23

#1185 chore: added Recorders #1020
  src/DB/product.json
Labels: level1, gssoc23

#1183 docs: Updated CONTRIBUTING.md by adding PR naming template #1167
  CONTRIBUTING.md
Labels: level1, gssoc23

#1143 chore: Name logo of FreeHit website, Fixes #804
  src/assets/darkmode-logo.png
  src/assets/footer-logo.png
  src/assets/footer-logo.webp
  src/assets/free-logo.webp
  src/assets/logo.png
  src/assets/mobileview.png
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/styles/Footer.css
  src/styles/header.css
  src/styles/index.css
Labels: level3, gssoc23

#1162 fix: made the dark mode button available on all pages #1142
  src/components/DarkMode.jsx
  src/components/Layout.jsx
  src/pages/Home.jsx
  src/styles/BackToTop.css
  src/styles/DarkMode.css
  src/styles/Home.css
Labels: level2, gssoc23

#1198 chore: Added Storybook #905
  src/DB/product.json
Labels: gssoc23

#1176 chore: Added Enggsolution #868
  src/DB/product.json
Labels: level1, gssoc23

#1105 feat: Created Browser Extention for to website
  extenstion/DB/product.json
  extenstion/back.png
  extenstion/index.html
  extenstion/link.png
  extenstion/logo.jpg
  extenstion/logo.png
  extenstion/logo128.jpg
  extenstion/logo16.jpg
  extenstion/logo48.jpg
  extenstion/manifest.json
  extenstion/script.js
  extenstion/style.css
Labels: level3, gssoc23

#1291 chore: Added Tools
  src/DB/product.json
Labels: level1, gssoc23

#1159 style: Search Area Design Improvement
  src/styles/header.css
  src/styles/index.css
Labels: level1, gssoc23

#1351 feat: Added the MIT License badge and changed the license section
  README.md
Labels: no-pr-activity

#1223 feat: feature added for start and end page arrow
  src/components/Pagination.jsx
  src/styles/Home.css
  src/styles/Pagination.css
Labels: level3, gssoc23

#1288 chore: adding link to the footer logo
  src/components/Footer.jsx
Labels: level1, gssoc23

#1329 chore: color of SVG icon changed
  src/styles/Home.css
Labels: level1, gssoc23, no-pr-activity

#1464 style: Added visibility to scrollup button #1287
  src/styles/BackToTop.css
Labels: level1, gssoc23

#1444 feat: open graph image add
  index.html
Labels: level1, gssoc23

#1472 fix: Capitalization of first letter #1330
  src/components/Card/GridView.jsx
  src/components/Card/ListView.jsx
Labels: level1, gssoc23

#1465 fix: Updated Github Logo Hover Effect Color
  src/styles/Footer.css
Labels: level1, gssoc23

#1413 feat: Update_product.json
  src/DB/product.json
Labels: no-pr-activity

#1349 chore: Tools for image generation added #1227
  src/DB/product.json
  src/utils/data/categories.js
  src/utils/data/filters.js
Labels: level1, gssoc23

#1490 fix: added share functionality #1458
  src/components/Card/GridView.jsx
  src/components/Card/ListView.jsx
Labels: level3, gssoc23

#1484 fix: bad contrast color of list item toggle button 🛠
  src/pages/Bookmarks.jsx
Labels: level1, gssoc23

#1524 fix: added the searchbar css #1520
  src/styles/header.css
Labels: level1, gssoc23

#1514 feat: Added Category 'API'
  src/DB/product.json
  src/utils/data/categories.js
  src/utils/data/filters.js
Labels: level1, gssoc23

#1423 fix: improved lighthouse score
  extenstion/index.html
  extenstion/logo.png
  extenstion/logo.webp
  extenstion/script.js
  public/sitemap.xml
  src/assets/darkmode-logo.png
  src/assets/darkmode-logo.webp
  src/assets/footer-logo.png
  src/assets/footer-logo.webp
  src/assets/logo.png
  src/assets/logo.webp
  src/assets/mobileview.png
  src/assets/mobileview.webp
  src/components/BackToTop.jsx
  src/components/Button.jsx
  src/components/Card/GridView.jsx
  src/components/Card/ListView.jsx
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/pages/Bookmarks.jsx
  src/pages/Home.jsx
  src/styles/Home.css
  src/styles/ListView.css
  src/styles/header.css
  src/styles/index.css
  src/utils/check_filters.js
Labels: level3, gssoc23
