Repository JasonDsouza212/free-hit, pull requests merged in 2023-06, with the labels that each got.

#423 Added UI/UX Tools Category with all required things
  src/DB/product.json
  src/components/Data/categories.jsx
Labels: level2, gssoc23

#436 resolve conflicts - Fuzzy Search
  src/App.jsx
Labels: level3, gssoc23

#402 refactor: filter with search params
  src/App.jsx
  src/components/Card/GridView.jsx
  src/components/Card/ListView.jsx
  src/components/bookmarks.jsx
  src/components/card.jsx
  src/components/header.jsx
  src/styles/header.css
Labels: level3, gssoc23

#441 IMPROVED HEADER
  src/components/header.jsx
  src/styles/header.css
  src/styles/index.css
Labels: level1, gssoc23

#444 Restructure the codebase
  src/App.jsx
  src/assets/1.png
  src/assets/2.png
  src/assets/3.png
  src/assets/4.png
  src/assets/business-presentation-1.png
  src/assets/coworking.png
  src/assets/designer-desk-2.png
  src/assets/footer-logo.png
  src/assets/free-logo.png
  src/assets/sad-face-2.png
  src/assets/sad-face.png
  src/components/BackToTop.jsx
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/components/Team.jsx
  src/components/TwitterButton.jsx
  src/components/aboutnav.jsx
  src/pages/About.jsx
  src/pages/Bookmarks.jsx
  src/pages/Community.jsx
  src/pages/Home.jsx
  src/pages/NotFound.jsx
  src/styles/About.css
  src/styles/BackToTop.css
  src/styles/Community.css
  src/styles/Footer.css
  src/styles/Home.css
  src/styles/NotFound.css
  src/styles/Team.css
  src/styles/index.css
  src/utils/data/categories.js
  src/utils/data/message.js
  src/utils/filter/filter_products.js
  src/utils/fuzzy_search/search.js
Labels: level3, gssoc23

#469 Added 3 more products to list
  src/DB/product.json
Labels: level1, gssoc23

#463 Fixed the redirect bug on clicking bookmark button
  src/components/Card/GridView.jsx
  src/components/Card/ListView.jsx
Labels: level2, gssoc23

#419 Add cuvette to remote jobs
  src/DB/product.json
Labels: level1, gssoc23

#459 feat: select multiple filters
  src/App.jsx
  src/components/Card/GridView.jsx
  src/components/Card/ListView.jsx
  src/components/Navbar.jsx
  src/pages/Bookmarks.jsx
  src/pages/Home.jsx
  src/styles/header.css
  src/utils/filter/filter_products.js
  src/utils/search/fuzzy_search.js
  src/utils/search/search_products.js
Labels: level3, gssoc23

#485 New tool added
  src/DB/product.json
Labels: gssoc23

#516 Meta tags added
  index.html
Labels: level2, gssoc23

#529 Fixed issue #501
  src/components/Card/GridView.jsx
  src/styles/Home.css
Labels: level2, gssoc23

#519 Improved visiblilty in sidebar of about
  src/components/Navbar.jsx
  src/styles/header.css
Labels: level1, gssoc23

#503 Issue#472
  src/components/Footer.jsx
  src/styles/Footer.css
Labels: level1, gssoc23

#476 added dall.e.2.0
  src/DB/product.json
Labels: level1, gssoc23

#462 Changed a bug in the list view
  src/components/Card/ListView.jsx
Labels: level2, gssoc23

#487 feat: add loader on Home page
  src/components/Loader.jsx
  src/pages/Home.jsx
  src/styles/Loader.css
Labels: level2, gssoc23

#535 cards-aligned-properly
  src/styles/Home.css
Labels: level2, gssoc23

#540 Fixes/about bg
  src/styles/Loader.css
  src/styles/Team.css
Labels: level1, gssoc23

#544 fix leetcode extension
  src/DB/product.json
Labels: level1, gssoc23

#545 fixes: about page sidebar font-style
  src/styles/header.css
Labels: level1, gssoc23

#559 Alt attributes added in img tags
  src/components/Card/GridView.jsx
  src/components/Card/ListView.jsx
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/pages/About.jsx
  src/pages/Bookmarks.jsx
  src/pages/Home.jsx
Labels: level1, gssoc23

#576 Added overleaf to resume builder
  package-lock.json
  src/DB/product.json
Labels: level1, gssoc23

#571 Adding new tool
  src/DB/product.json
Labels: level1, gssoc23

#568 Added Google Fonts
  src/DB/product.json
Labels: level1, gssoc23

#547 Correct Misspelling of Tool Name
  src/DB/product.json
Labels: level1, gssoc23

#534 Magic Eraser added to Free-Hit issue #528 GSSOC 2k23
  src/DB/product.json
Labels: level1, gssoc23

#554 Added a new category of coding platforms to the website
  src/DB/product.json
  src/utils/data/categories.js
  src/utils/data/filters.js
Labels: level1, gssoc23

#581 added the web category inside filters.js
  src/utils/data/filters.js
Labels: level1, gssoc23

#593 fixes: remove duplicates from products.json
  src/DB/product.json
Labels: level1, gssoc23

#600 Readme updated
  README.md
Labels: level1, gssoc23

#605 Refactor: use Search params for searching and clean the code in app component
  src/App.jsx
  src/components/Card/GridView.jsx
  src/components/Card/ListView.jsx
  src/components/Navbar.jsx
  src/pages/Bookmarks.jsx
  src/pages/Home.jsx
Labels: level3, gssoc23

#619 fixes: search suggestions bug
  src/pages/Bookmarks.jsx
  src/pages/Home.jsx
Labels: level2, gssoc23

#617 Added website for developer for practice and learning purpose
  src/DB/product.json
Labels: level1, gssoc23

#629 enhance: add pagination options at top
  src/components/Pagination.jsx
  src/pages/Home.jsx
  src/styles/Home.css
  src/styles/Pagination.css
Labels: level3, gssoc23

#659 add w3schools
  src/DB/product.json
Labels: level1, gssoc23

#655 Adding new Ed Tech Website
  src/DB/product.json
Labels: level1, gssoc23

#650 added new website
  src/DB/product.json
Labels: level1, gssoc23

#613 Balasarvan12 #603
  src/DB/product.json
Labels: level1, gssoc23

#660 Not Found Page Improved
  src/assets/error.png
  src/pages/NotFound.jsx
  src/styles/NotFound.css
Labels: level2, gssoc23

#649 responsiveness fixed for small devices
  src/styles/index.css
Labels: Needs confirmation ‼️

#682 Added Design.AI,Myperfectresume,VisualCV and some other sites.
  src/DB/product.json
Labels: level1, gssoc23

#677 Added some AI tools like Slidesai, Uizard, Autodraw, Starrytars
  src/DB/product.json
Labels: level1, gssoc23

#683 added a sitemap to the website
  public/robots.txt
  public/sitemap.xml
Labels: level2, gssoc23

#712 Added Otter and Runway AI tool
  src/DB/product.json
Labels: level1, gssoc23

#715 adding google bard
  src/DB/product.json
Labels: level1, gssoc23

#716 Update About.jsx
  src/pages/About.jsx
Labels: level1, gssoc23

#713 Added the new JSONView extension by Parmesh Bhatt.
  src/DB/product.json
Labels: level1, gssoc23

#678 refactor: use layout component
  src/App.jsx
  src/components/Layout.jsx
  src/components/Navbar.jsx
Labels: level2, gssoc23

#679 Fixed #628, enhanced styling
  src/styles/header.css
Labels: level1, gssoc23

#744 Adding class central.
  src/DB/product.json
Labels: level1, gssoc23

#755 Added frontend mentor website #747
  src/DB/product.json
Labels: level1, gssoc23

#703 Added workflow
  .github/workflows/linting.yml
Labels: level2, gssoc23

#761 Automatically close old issues
  .github/workflows/close_old_issues.yml
Labels: level2, gssoc23

#759 Added Momentum to extensions
  src/DB/product.json
Labels: level1, gssoc23

#771 Converted png format to webp format
  CONTRIBUTING.md
  src/assets/1.png
  src/assets/1.webp
  src/assets/2.png
  src/assets/2.webp
  src/assets/3.png
  src/assets/3.webp
  src/assets/4.png
  src/assets/4.webp
  src/assets/business-presentation-1.png
  src/assets/business-presentation-1.webp
  src/assets/coworking.png
  src/assets/coworking.webp
  src/assets/designer-desk-2.png
  src/assets/designer-desk-2.webp
  src/assets/error.png
  src/assets/error.webp
  src/assets/footer-logo.png
  src/assets/footer-logo.webp
  src/assets/free-logo.png
  src/assets/free-logo.webp
  src/assets/sad-face-2.png
  src/assets/sad-face-2.webp
  src/assets/sad-face.png
  src/assets/sad-face.webp
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/components/Team.jsx
  src/pages/About.jsx
  src/pages/Bookmarks.jsx
  src/pages/Home.jsx
  src/pages/NotFound.jsx
Labels: level2, gssoc23

#786 BALASARVAN12-#763
  src/DB/product.json
Labels: level1, gssoc23

#803 [Feat]Add a new tool(Pomodoro tool) to increase user productivity[gssoc'23]
  src/DB/product.json
Labels: level1, gssoc23

#828 Added usaco website
  src/DB/product.json
Labels: level1, gssoc23

#768 Free Icons - an useful tool is added
  src/DB/product.json
Labels: level1, gssoc23

#769 Spinbot-an useful tool
  src/DB/product.json
Labels: level1, gssoc23

#790 Added Reactplay.io
  src/DB/product.json
Labels: level1, gssoc23

#805 feat: add list and grid view on bookmarks page
  src/pages/Bookmarks.jsx
Labels: level2, gssoc23

#810 Update product.json
  src/DB/product.json
Labels: level1, gssoc23

#811 add Walkccc website
  src/DB/product.json
Labels: level1, gssoc23

#814 Add new website Eventbrite for hackathons update
  src/DB/product.json
Labels: level1, gssoc23

#842 Aicolor.co added
  src/DB/product.json
Labels: level1, gssoc23

#860 Added Javascript.info
  src/DB/product.json
Labels: level1, gssoc23

#859 Added foundit.in [Gssoc'23)
  src/DB/product.json
Labels: gssoc23

#843 Added Bitwarden
  src/DB/product.json
Labels: level1, gssoc23

#846 added vegamovies website
  src/DB/product.json
Labels: level1, gssoc23

#942 Added new tools
  src/DB/product.json
Labels: level1, gssoc23

#832 Added GSAP-GreenStock Website
  src/DB/product.json
Labels: level1, gssoc23

#971 addition of sejda, hdtoday, myflixer
  src/DB/product.json
Labels: Add tool 🛠️, level1, gssoc23

#962 Testing
  src/DB/product.json
Labels: level1, gssoc23

#968 Added resources issue#961
  src/DB/product.json
Labels: level1, gssoc23

#945 Added Jobscan ATS Resume Checker Website
  src/DB/product.json
Labels: level1, gssoc23

#946 Added cryptozombies website to free-hit
  src/DB/product.json
Labels: level1, gssoc23

#944 Added Resume worded Website
  src/DB/product.json
Labels: level1, gssoc23

#923 Added BitDegree
  src/DB/product.json
Labels: level1, gssoc23

#880 VLC media Player Added
  src/DB/product.json
Labels: level1, gssoc23

#831 Added the Internshala remote jobs by Parmesh Bhatt
  src/DB/product.json
Labels: level1, gssoc23, no-pr-activity

#807 I have added devfolio,hackclub,mlh,devpost and unstop to coding in the coding tool
  src/DB/product.json
Labels: level1, gssoc23

#949 Added Spline AI related to issue-924
  src/DB/product.json
Labels: good first issue, Add tool 🛠️, level1, gssoc23

#979 [CHORE]: ADD COLOR LEAP FRONTEND TOOL ✨
  src/DB/product.json
Labels: Add tool 🛠️, level1, gssoc23
